# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
#
jobs:
  after-commit:
    steps:
      - run:
        command: |
          echo after commit
  job-welcom:
    steps:
      - run:
        command: |
          echo job welcom

workflows:
  # Name the workflow "welcome"
  commit:
    jobs:
      - after-commit
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - job-welcom
